apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: { app: backend }
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
        - name: backend-container
          image: kiranacr.azurecr.io/week08/backend:latest   # staging will override to :develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: { app: backend }
spec:
  selector: { app: backend }
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
