name: reusable-ci

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      node-version:
        type: string
        default: '20'
      run-tests:
        type: boolean
        default: true
      build-docker:
        type: boolean
        default: false
      image-name:
        type: string
        default: ''
      docker-tag:
        type: string
        default: ''

jobs:
  ci:
    name: CI - ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect package.json
        id: detect
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f package.json ]; then
            echo "has_pkg=true" >> $GITHUB_OUTPUT
          else
            echo "has_pkg=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.detect.outputs.has_pkg == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install
        if: steps.detect.outputs.has_pkg == 'true'
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Lint
        if: steps.detect.outputs.has_pkg == 'true'
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint --if-present

      - name: Test
        if: steps.detect.outputs.has_pkg == 'true' && inputs.run-tests
        working-directory: ${{ inputs.working-directory }}
        run: npm test --if-present -- --ci

  docker:
    name: Docker build/publish - ${{ inputs.image-name }}
    if: inputs.build-docker
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug – verify Dockerfile exists
        run: |
          echo "CWD=$(pwd)"
          echo "WD=${{ inputs.working-directory }}"
          ls -la
          ls -la "${{ inputs.working-directory }}"
          test -f "${{ inputs.working-directory }}/Dockerfile" || (echo "Missing Dockerfile at ${{ inputs.working-directory }}/Dockerfile" && exit 1)

      - name: Docker Login (skip on PRs)
        if: github.event_name != 'pull_request'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and (maybe) push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/${{ inputs.image-name }}:${{ inputs.docker-tag != '' && inputs.docker-tag || github.ref_name }}
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/${{ inputs.image-name }}:sha-${{ github.sha }}
