  docker:
    name: Docker build/publish - ${{ inputs.image-name }}
    if: inputs.build-docker
    needs: ci
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v4

      # Make sure Buildx is properly installed/initialized
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug – verify Dockerfile exists
        run: |
          echo "Expecting: ${{ inputs.working-directory }}/Dockerfile"
          ls -la
          ls -la "${{ inputs.working-directory }}"
          test -f "${{ inputs.working-directory }}/Dockerfile"

      - name: Docker Login (skip on PRs)
        if: github.event_name != 'pull_request'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          no-cache: true
          # Disable features that often trigger the HTTP/2 RST_STREAM error
          provenance: false
          sbom: false
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/${{ inputs.image-name }}:${{ inputs.docker-tag || github.ref_name }}
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/${{ inputs.image-name }}:sha-${{ github.sha }}
