name: reusable-ci

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      node-version:
        type: string
        default: '20'
      run-tests:
        type: boolean
        default: true
      build-docker:
        type: boolean
        default: false
      image-name:
        type: string
        default: ''
      docker-tag:
        type: string
        default: ''

jobs:
  ci:
    name: CI - ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect package.json
        id: detect
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f package.json ]; then echo "has_pkg=true" >> $GITHUB_OUTPUT; else echo "has_pkg=false" >> $GITHUB_OUTPUT; fi

      - if: steps.detect.outputs.has_pkg == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - if: steps.detect.outputs.has_pkg == 'true'
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - if: steps.detect.outputs.has_pkg == 'true'
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint --if-present

      - if: steps.detect.outputs.has_pkg == 'true' && inputs.run-tests
        working-directory: ${{ inputs.working-directory }}
        run: npm test --if-present -- --ci

  docker:
    name: Docker build/publish - ${{ inputs.image-name }}
    if: inputs.build-docker
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Dockerfile is present
        run: |
          echo "Expecting: ${{ inputs.working-directory }}/Dockerfile"
          ls -la "${{ inputs.working-directory }}"
          test -f "${{ inputs.working-directory }}/Dockerfile"

      # Login to ACR (you can keep azure/docker-login, this one is also fine)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Classic docker build (no buildx/BuildKit) + push
      - name: Build & push (classic docker)
        env:
          DOCKER_BUILDKIT: 0
        run: |
          set -euo pipefail
          IMAGE_BASE="${{ secrets.ACR_LOGIN_SERVER }}/week08/${{ inputs.image-name }}"
          TAG1="${IMAGE_BASE}:${{ inputs.docker-tag || github.ref_name }}"
          TAG2="${IMAGE_BASE}:sha-${{ github.sha }}"
          echo "Building ${TAG1} and ${TAG2} from ${{ inputs.working-directory }}"
          docker build --pull \
            -f "${{ inputs.working-directory }}/Dockerfile" \
            -t "${TAG1}" -t "${TAG2}" \
            "${{ inputs.working-directory }}"

          # Push both tags (manual workflow isn't a PR, so pushing is fine)
          docker push "${TAG1}"
          docker push "${TAG2}"
