name: CD – Deploy Backend to AKS

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "k8s/**"
      - ".github/workflows/backend-cd.yml"

concurrency:
  group: backend-cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  deployments: write

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}   # e.g. registryw8.azurecr.io
  IMAGE_TAG: ${{ github.sha }}
  K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE || vars.K8S_NAMESPACE || 'default' }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: |
          REG_NAME=$(echo "${{ env.ACR_LOGIN_SERVER }}" | cut -d. -f1)
          az acr login --name "$REG_NAME"

      - name: Build backend images
        run: |
          docker build -t $ACR_LOGIN_SERVER/product_service:${{ env.IMAGE_TAG }} backend/product_service
          docker build -t $ACR_LOGIN_SERVER/order_service:${{ env.IMAGE_TAG }}   backend/order_service

      - name: Push backend images
        run: |
          docker push $ACR_LOGIN_SERVER/product_service:${{ env.IMAGE_TAG }}
          docker push $ACR_LOGIN_SERVER/order_service:${{ env.IMAGE_TAG }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name:  ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Apply manifests
        run: |
          kubectl -n "${{ env.K8S_NAMESPACE }}" apply -f k8s/

      - name: Update deployments to new images
        run: |
          NS="${{ env.K8S_NAMESPACE }}"
          kubectl -n "$NS" set image deployment/product-service-w08e1 *=$ACR_LOGIN_SERVER/product_service:${{ env.IMAGE_TAG }} --record=true
          kubectl -n "$NS" set image deployment/order-service-w08e1   *=$ACR_LOGIN_SERVER/order_service:${{ env.IMAGE_TAG }} --record=true

      - name: Wait for rollout
        run: |
          NS="${{ env.K8S_NAMESPACE }}"
          kubectl -n "$NS" rollout status deployment/product-service-w08e1 --timeout=300s
          kubectl -n "$NS" rollout status deployment/order-service-w08e1   --timeout=300s

      - name: Diagnostics (on failure)
        if: failure()
        run: |
          NS="${{ env.K8S_NAMESPACE }}"
          echo "=== Deploy/RS/Pods/Services ==="
          kubectl -n "$NS" get deploy,rs,po,svc -o wide || true
          echo "=== Describe deployments ==="
          kubectl -n "$NS" describe deploy product-service-w08e1 || true
          kubectl -n "$NS" describe deploy order-service-w08e1   || true
          echo "=== Recent events ==="
          kubectl -n "$NS" get events --sort-by=.lastTimestamp | tail -n 100 || true
          echo "=== Pod logs (first pod per app) ==="
          P=$(kubectl -n "$NS" get po -l app=product-service-w08e1 -o name | head -n1); [ -n "$P" ] && kubectl -n "$NS" logs "$P" --all-containers --tail=200 || true
          P=$(kubectl -n "$NS" get po -l app=order-service-w08e1   -o name | head -n1); [ -n "$P" ] && kubectl -n "$NS" logs "$P" --all-containers --tail=200 || true

      - name: Show cluster state
        if: always()
        run: kubectl -n "${{ env.K8S_NAMESPACE }}" get deploy,po,svc -o wide

      - name: Azure logout
        if: always()
        run: az logout
