on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      safe: ${{ steps.s.outputs.safe }}
    steps:
      - uses: actions/checkout@v4
      - id: s
        run: |
          RAW="${GITHUB_REF_NAME}"
          SAFE="${RAW//\//-}"
          echo "safe=$SAFE" >> "$GITHUB_OUTPUT"

  backend_order:
    uses: ./.github/workflows/_reusable-ci.yml
    needs: tag
    secrets: inherit
    with:
      working-directory: backend/order_service
      run-tests: false
      build-docker: true
      image-name: backend-order
      docker-tag: ${{ needs.tag.outputs.safe }}

  backend_product:
    uses: ./.github/workflows/_reusable-ci.yml
    needs: [tag, backend_order]   # wait for backend_order to finish
    secrets: inherit
    with:
      working-directory: backend/product_service
      run-tests: false
      build-docker: true
      image-name: backend-product
      docker-tag: ${{ needs.tag.outputs.safe }}

  frontend:
    uses: ./.github/workflows/_reusable-ci.yml
    needs: [tag, backend_product] # wait for backend_product to finish
    secrets: inherit
    with:
      working-directory: frontend
      run-tests: false
      build-docker: true
      image-name: frontend
      docker-tag: ${{ needs.tag.outputs.safe }}
