name: CI only (manual)

on:
  workflow_dispatch:

jobs:
  frontend:
    uses: ./.github/workflows/_reusable-ci.yml
    secrets: inherit
    with:
      working-directory: frontend
      run-tests: false
      build-docker: false
      image-name: frontend

  backend-order:
    uses: ./.github/workflows/_reusable-ci.yml
    secrets: inherit
    with:
      working-directory: backend/order_service
      run-tests: false
      build-docker: false
      image-name: backend-order

  backend-product:
    uses: ./.github/workflows/_reusable-ci.yml
    secrets: inherit
    with:
      working-directory: backend/product_service
      run-tests: false
      build-docker: false
      image-name: backend-product
