name: Build images (manual)

on:
  workflow_dispatch:

jobs:
  frontend:
    uses: kiran497/week08/.github/workflows/_reusable-ci.yml@main
    secrets: inherit
    with:
      working-directory: frontend
      run-tests: false
      build-docker: true
      image-name: frontend

  backend-order:
    uses: kiran497/week08/.github/workflows/_reusable-ci.yml@main
    secrets: inherit
    with:
      working-directory: backend/order_service
      run-tests: false
      build-docker: true
      image-name: backend-order

  backend-product:
    uses: kiran497/week08/.github/workflows/_reusable-ci.yml@main
    secrets: inherit
    with:
      working-directory: backend/product_service
      run-tests: false
      build-docker: true
      image-name: backend-product
