name: PR CI
on:
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
  push:
    branches: [ 'feature/**' ]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    uses: ./.github/workflows/_reusable-ci.yml
    with:
      working-directory: frontend
      run-tests: true
      build-docker: false

  backend:
    uses: ./.github/workflows/_reusable-ci.yml
    with:
      working-directory: backend
      run-tests: true
      build-docker: false
