name: CI
on:
  pull_request: { branches: [develop, main], paths-ignore: ['**/*.md', '.github/**'] }
  push:         { branches: [develop],       paths-ignore: ['**/*.md', '.github/**'] }
permissions: { contents: read }
jobs:
  backend:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      language: node
      workdir: backend
      test: npm test --if-present -- --ci
      build: npm run build --if-present
  frontend:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      language: node
      workdir: frontend
      test: npm test --if-present -- --ci
      build: npm run build --if-present
