name: CI

# Run this only on PUSH (feature/fix/chore branches). PRs use ci-pr.yml.
on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  frontend:
    uses: ./.github/workflows/_reusable-ci.yml   # <— underscore!
    with:
      working-directory: frontend
      run-tests: false
      build-docker: false

  backend:
    uses: ./.github/workflows/_reusable-ci.yml   # <— underscore!
    with:
      working-directory: backend
      run-tests: true
      build-docker: false
