name: Deploy to Production (AKS)

on:
  push:
    branches: [ main ]      # <— only main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      - uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            k8s/frontend.yaml
            k8s/backend.yaml
          images: |
            frontend-container=${{ secrets.ACR_LOGIN_SERVER }}/week08/frontend:main
            backend-container=${{ secrets.ACR_LOGIN_SERVER }}/week08/backend:main
