name: Release images (ACR)

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}   # keep as secret
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push FRONTEND image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/frontend:${{ github.ref_name == 'main' && 'main' || 'develop' }}
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/frontend:latest

      - name: Build & push BACKEND image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/backend:${{ github.ref_name == 'main' && 'main' || 'develop' }}
            ${{ secrets.ACR_LOGIN_SERVER }}/week08/backend:latest
