name: Release images (ACR)

on:
  push:
    branches: [ develop, main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set tag by branch
        id: tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TAG=main" >> $GITHUB_OUTPUT
          else
            echo "TAG=develop" >> $GITHUB_OUTPUT
          fi

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/week08/frontend:${{ steps.tag.outputs.TAG }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/week08/backend:${{ steps.tag.outputs.TAG }}
