name: Release images (ACR)

on:
  push:
    branches: [ develop, main ]

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}      # kiranacr.azurecr.io
  USERNAME: ${{ secrets.ACR_USERNAME }}
  PASSWORD: ${{ secrets.ACR_PASSWORD }}
  NS: week08
  TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'develop' }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NS }}/frontend:${{ env.TAG }}

      # ⬇Build backend from the Python service folder
      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend/order_service
          file: ./backend/order_service/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NS }}/backend:${{ env.TAG }}
