name: Release images (ACR)

on:
  push:
    branches: [ develop, main ]

permissions:
  contents: read
  id-token: write   # needed by some actions; fine to keep

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. kiranacr.azurecr.io
  USERNAME: ${{ secrets.ACR_USERNAME }}
  PASSWORD: ${{ secrets.ACR_PASSWORD }}
  NS: week08
  TAG: ${{ github.ref_name == 'main' && 'latest' || 'develop' }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      # ---- Frontend image ----
      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          # if your frontend has a Dockerfile at ./frontend/Dockerfile this works.
          # remove "file:" line if your Dockerfile name is exactly "Dockerfile".
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NS }}/frontend:${{ env.TAG }}

      # ---- Backend image ----
      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NS }}/backend:${{ env.TAG }}
