name: Release (Build & Push)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "!**/*.md"

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - { path: backend,  image: backend }
          - { path: frontend, image: frontend }

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.component.path }}
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/${{ matrix.component.image }}:${{ github.sha }}
            ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/${{ matrix.component.image }}:latest
