name: Release images (ACR)

on:
  push:
    branches: [ develop, main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. kiranacr.azurecr.io
  USERNAME: ${{ secrets.ACR_USERNAME }}
  PASSWORD: ${{ secrets.ACR_PASSWORD }}
  NS: week08
  TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'develop' }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NS }}/frontend:${{ env.TAG }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NS }}/backend:${{ env.TAG }}
