name: Release images (ACR)

on:
  push:
    branches: [ develop, main ]

permissions:
  contents: read
  id-token: write   # required for azure/login OIDC

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. kiranacr.azurecr.io
  NS: week08
  TAG: ${{ github.ref_name == 'main' && 'latest' || 'develop' }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        shell: bash
        run: |
          set -euo pipefail
          ACR_NAME="$(echo "$REGISTRY" | cut -d. -f1)"
          az acr login --name "$ACR_NAME"

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NS }}/frontend:${{ env.TAG }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NS }}/backend:${{ env.TAG }}
