name: reusable-ci

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      workdir:
        required: true
        type: string
      test:
        required: true
        type: string
      build:
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workdir }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (if JS)
        if: ${{ inputs.language == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: ${{ inputs.workdir }}/package-lock.json

      - name: Install deps (ci or install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping install"
          fi

      - name: Lint (non-blocking)
        run: |
          if [ -f package.json ] && npm run | grep -q " lint"; then
            npm run lint || echo "lint failed (non-blocking)"
          else
            echo "no lint script, skipping"
          fi

      - name: Test (non-blocking)
        run: |
          if [ -f package.json ] && npm run | grep -q " test"; then
            npm test -- --ci || echo "tests failed or not configured (non-blocking)"
          else
            echo "no test script, skipping"
          fi

      - name: Build
        run: |
          if [ -f package.json ] && npm run | grep -q " build"; then
            npm run build
          else
            echo "no build script, skipping"
          fi

      - name: Upload artifact (if build outputs exist)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.workdir }}-build
          path: |
            ${{ inputs.workdir }}/dist
            ${{ inputs.workdir }}/build
            !**/node_modules/**
          if-no-files-found: ignore
