name: reusable-ci

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      workdir:
        required: true
        type: string
      test:
        required: true
        type: string
      build:
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workdir }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (if JS)
        if: ${{ inputs.language == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: ${{ inputs.workdir }}/package-lock.json

      - name: Install
        run: |
          if [ -f package-lock.json ]; then npm ci; fi

      - name: Lint
        run: |
          if [ -f package.json ]; then npm run lint --if-present; fi

      - name: Test
        run: ${{ inputs.test }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.workdir }}-build
          path: |
            ${{ inputs.workdir }}/dist
            ${{ inputs.workdir }}/build
            !**/node_modules/**
